### ISSUE TITLE
使用arm_linux_gnueabihf模式编译出的 demo  执行都报类似错误

### ISSUE THREAD

**Issue by Franke-lishaohui** [pili-engineering/QNRTC-Linux#7]
QNRTC-Linux-master demo
版本号为：SDK 版本:5.0.1-1fa966f
使用arm_linux_gnueabihf模式编译出的 demo 执行都报类似错误

![image](https://user-images.githubusercontent.com/75160855/175474691-d6948b7f-4cdd-470d-8512-3d2b7fc1450c.png)

**Comment by chenqian-dev** [comment]
> QNRTC-Linux-master demo
> 版本号为：SDK 版本:5.0.1-1fa966f
> 使用arm_linux_gnueabihf模式编译出的 demo 执行都报类似错误
> 
> 
> ![image](https://user-images.githubusercontent.com/75160855/175474691-d6948b7f-4cdd-470d-8512-3d2b7fc1450c.png)
> 
> 

请安装并启用 pulseaudio  库

**Comment by Franke-lishaohui** [comment]
好的，谢谢！



Regards,

李绍辉 | 硬件开发部
M: (86) 133 8645 7728
E:   ***@***.***
W:  www.weds.com.cn
 
山东威尔数据股份有限公司
地址: 山东省烟台市莱山区瑞达路8号
诚信务实、合作共赢是我们公司价值观的重要内容，我们整个开发、采购、生产、销售环节接受大家关于廉洁、诚信方面的监督
***@***.***
 
发件人： phelps
发送时间： 2022-06-24 20:42
收件人： pili-engineering/QNRTC-Linux
抄送： Franke-lishaohui; Author
主题： Re: [pili-engineering/QNRTC-Linux] 使用arm_linux_gnueabihf模式编译出的 demo 执行都报类似错误 (Issue #7)
QNRTC-Linux-master demo
版本号为：SDK 版本:5.0.1-1fa966f
使用arm_linux_gnueabihf模式编译出的 demo 执行都报类似错误
请安装并启用 pulseaudio 库
